### ISSUE TITLE
Pink 24ths

### ISSUE THREAD

**Issue by ghost** [HURG-IIDX/Noteskin-Workshop-Enchantment#3]
I commented on Discord about pink 24ths. I copied the default and shifted 24ths pinker/lighter and 48ths pinker/lightest:

![](https://raw.githubusercontent.com/unnoticeable/Noteskin-Workshop-Enchantment/b1956810e4f97f966267626faa2fc539f04e1143/Customizations/Arrows/Default%20Pink-24-48/_Down%20Tap%20Note%20(doubleres)%2016x8.png)

**Comment by HURG-IIDX** [comment]
I'll base it on this but im gonna make it myself to make sure the arrow colors are consistent between variants (like the frames for the shadow variant)

**Comment by HURG-IIDX** [comment]
https://github.com/HURG-IIDX/Noteskin-Workshop-Enchantment/commit/ba4047ade8a63bde6349b5bfd95f26a6310a59df

**Comment by HURG-IIDX** [comment]
https://github.com/HURG-IIDX/Noteskin-Workshop-Enchantment/commit/ba4047ade8a63bde6349b5bfd95f26a6310a59df
